### ISSUE TITLE
Resource file will not reload when changed and saved

### ISSUE THREAD

**Issue by kwomba** [stefanegli/ResxFormatter#4] opened 2021-11-29 22:54 UTC
**Describe the bug**
Resource file will not reload when changed and saved when setting `Reload file after saving` is set to `AfterModification`

**To Reproduce**
- Set "Reload file after saving" to "`AfterModification`"
- Change a resource file
- Save resource file

**Expected behavior**
Changed resource file is reloaded

**Screenshots**
n.a.

**Desktop (please complete the following information):**
n.a.

**Smartphone (please complete the following information):**
n.a.

**Additional context**
Line 88 in `ResxFormatterPackage.cs` should read:
`                if ((formatter.Run(document.Path) && settings.ReloadFile == ReloadMode.AfterModification)`

**Comment by stefanegli** [comment] 2021-12-02 22:38
Thanks. I will try to fix this as soon as possible :-)

**Comment by stefanegli** [comment] 2021-12-05 12:10
The problem is fixed in version 1.2.

**Closed by stefanegli** 2021-12-05 12:10 UTC
