### ISSUE TITLE
Reorder Alphabetically

### ISSUE THREAD

**Issue by MrSanderSi** [stefanegli/ResxFormatter#10] opened 2023-02-13 09:27 UTC
When I update from 2.0.68 to 3.0.76 I noticed that newly added resx entries no longer reordered themselves alphabetically, older entries stayed as is. The designer file is fine and orders itself correctly. 

**Desktop**
 - OS: Windows 11 Enterprise
 - Version 10.0.22000 Build 22000
 - IDE: Visual Studio Professional 2022

**Additional context**
Moving back to 2.0.68 worked. I also tried to make 3.0.76 work with changing settings in Tools -> options -> ResxFormatter -> General and with making changes in .editorconfig

**Comment by stefanegli** [comment] 2023-02-15 16:16
Do you see anything in the output window? There should be a source "ResxFormatter" and it should show some output if a file (any type) is saved. If such an output is shown then there is something wrong the EditorConfig settings (maybe you can post the settings that you are using).

If no event is visible in the output window, you can try to use the _Extensions > ResxFormatter > Format all files in solution_ menu (make sure that you can revert the changes if necessary). This would allow us to see if EditorConfig Settings are working properly. It it possible that re-installing the extension fixes the problem that no events are received by the package.

**Comment by stefanegli** [comment] 2023-02-17 06:47
Seems to be a bug in the EditorConfig package that I am using. I updated to the latest version which seems to have a fix for this problem. If you like you can try to use the CI build that contains update:
https://www.vsixgallery.com/extension/ResxFormatter.61507132-4401-47b1-9950-575e43b964c6/

**Comment by lKoTl** [comment] 2023-02-17 10:56
Yes, I can confirm that it solves the problem.

**Comment by stefanegli** [comment] 2023-02-17 15:08
@MrSanderSi I will close this issue for now, a proper release will follow but for now you can use the CI Build. Just let me know if the CI Build does not fix the problem in your case.

**Closed by stefanegli** 2023-02-17 15:08 UTC
Labels: bug
